name: creo_touch
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.2
  go_router: ^14.0.0
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  web_socket_channel: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: 
  custom_lint:
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
